name: CI/CD - Pinguin

on:
  push:
    branches:
      - main

jobs:
  build-n-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: ./pinguin/app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run unit tests (placeholder for now)
      - name: Run unit tests
        run: |
          echo "✅ Running simple unit tests"
          python -m unittest discover -s pinguin/app -p "*_test.py" || echo "No tests yet"

  package-e2e-publish:
    runs-on: ubuntu-latest
    needs: build-n-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 5. Build docker image
      - name: Build Docker image
        run: |
          docker build -t pinguin:test ./pinguin/app

      # 6. Run docker-compose for integration tests
      - name: Run integration tests
        run: |
          docker compose -f pinguin/docker-compose.yml up -d --build
          sleep 20
          curl -f http://localhost:5000 || (docker compose -f pinguin/docker-compose.yml logs && exit 1)
          docker compose -f pinguin/docker-compose.yml down

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 7. Authenticate to AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 8. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 9. Build, tag, and push image
      - name: Build, tag, and push
        run: |
          IMAGE_URI=${{ steps.ecr.outputs.registry }}/portfolio/pinguin:${{ github.sha }}
          docker build -t $IMAGE_URI ./pinguin/app
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # 10. Deploy to K8S
      - name: Update K8S deployment
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            k8s-manifests/deploy-app.yaml
          images: ${{ env.IMAGE_URI }}
          namespace: default
